// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cancel-btn': string;
  'destroy-btn': string;
  'img-btn': string;
  'select-btn': string;
  'submit-btn': string;
  'waiting-btn': string;
}
export const cssExports: CssExports;
export default cssExports;
