// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'invisible': string;
  'textbox': string;
  'textbox-appear-opacity': string;
  'textbox-appear-scale': string;
  'textbox-backdrop': string;
  'textbox-cancel': string;
  'textbox-content': string;
  'textbox-select': string;
  'textbox-title-bar': string;
  'textbox-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
