// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'text-box-cancel-btn': string;
  'text-box-destroy-btn': string;
  'text-box-select-btn': string;
  'text-box-submit-btn': string;
  'text-box-waiting-btn': string;
}
export const cssExports: CssExports;
export default cssExports;
